on:
  push:
  pull_request:

jobs:
  test:
    name: "run flutter test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.8"

      - run: echo ${{ secrets.ENV }} | base64 -d > .env
      - run: flutter --version

      - run: flutter pub get
      - run: flutter analyze

      - run: "chmod +x test.sh"
      - run: "./test.sh"

  integration_test:
    name: "run flutter integration test"
    runs-on: macos-latest
    needs: test
    strategy:
      matrix:
        api-level: [31]
        target: [default]

    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.8"

      - run: echo ${{ secrets.ENV }} | base64 -d > .env
      - run: echo ${{ secrets.KEY_PROPERTIES }} | base64 -d > android/key.properties
      - run: echo ${{ secrets.KEYSTONE_JKS }} | base64 -d > android/app/keystone.jks
      - run: echo ${{ secrets.GOOGLE_SERVICES }} | base64 -d > android/app/google-services.json

      - run: flutter --version
      - run: flutter pub get

      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: chmod +x ./integration_test/integration_test.sh && ./integration_test/integration_test.sh

      - name: Upload Screenshots during integration test
        uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: screenshots/

      - uses: actions/download-artifact@v3
        with:
          name: app-screnshoot
          path: screenshots/
